// Generated by CoffeeScript 2.7.0
(function() {
  var Perfil, colaborador;

  Perfil = class Perfil {
    constructor(nome, cargo) {
      this.nome = nome;
      this.cargo = cargo;
    }

    descrever() {
      return `Funcionário: ${this.nome} | Cargo: ${this.cargo}`;
    }

  };

  colaborador = new Perfil("Ana Souza", "Desenvolvedora Frontend");

  console.log(colaborador.descrever());

}).call(this);
